---
server:
  ssl:
    enabled: false
  servlet:
    context-path: '/emotionsRoute'
spring:
    profiles: development
    datasource: 
      url: 'jdbc:mysql://localhost:3306/emotionsRoute?useSSL=false'
      username: root
      password: root
      initialization-mode: always
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
