---
server:
  ssl:
    enabled: false
  servlet:
    context-path: '/emotionsRoute'
spring:
    profiles: development
    datasource: 
      url: 'jdbc:mysql://172.17.0.3:3306/emotionsRoute'
      username: root
      password: root
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
